# Generated by Django 3.1.2 on 2020-10-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto Principal')),
                ('texto_secundario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto Principal')),
                ('texto_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto Principal')),
                ('texto_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto Principal')),
            ],
        ),
    ]
