# Generated by Django 3.1.2 on 2020-10-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_acessoria_contabil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textosite',
            name='dt_ultima_alteracao',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data Ultima Alterção'),
        ),
        migrations.AddField(
            model_name='textosite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='textosite',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='textosite',
            name='instagran',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='textosite',
            name='telcelular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº telefone celular'),
        ),
        migrations.AddField(
            model_name='textosite',
            name='telfixo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº telefone fixo'),
        ),
        migrations.AddField(
            model_name='textosite',
            name='twiter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twiter'),
        ),
        migrations.AddField(
            model_name='textosite',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Whatsapp'),
        ),
        migrations.AlterField(
            model_name='textosite',
            name='texto_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto 03'),
        ),
        migrations.AlterField(
            model_name='textosite',
            name='texto_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto 04'),
        ),
        migrations.AlterField(
            model_name='textosite',
            name='texto_secundario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto Secundário'),
        ),
    ]
