# Generated by Django 3.1.2 on 2020-10-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_acessoria_contabil', '0002_auto_20201006_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textosite',
            options={'verbose_name': 'Texto do Site', 'verbose_name_plural': 'Textos do Site'},
        ),
        migrations.AddField(
            model_name='textosite',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
    ]
